### ISSUE TITLE
is Travis used?

### ISSUE THREAD

**Issue by MOJOliciousFTW** [frdedynamics/hvl_robotics_website#9]
There is a `.travis.yml` file
https://github.com/frdedynamics/hvl_robotics_website/blob/master/.travis.yml
but there is also a github workflow 
https://github.com/frdedynamics/hvl_robotics_website/blob/master/.github/workflows/jekyll.yml
are they completley different? Is Travis used? Should Travis use be replaced by github workflows?

**Comment by dschaele** [comment]
don't know, have never really checked how this template works. there is quite a bit of unused stuff in this repo i suppose

**Comment by MOJOliciousFTW** [comment]
cool 👍

AFAIK none of us use Travis (I did years ago, not anymore) https://www.travis-ci.com/

the .travis.yml does no harm, not worth the time to tidy up by removing this file and other not used template files.

Thanks for answering! 🤝
